version: "3.9"

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - ./app:/src/app  # Bind the app directory for hot reloading
    ports:
      - "8000:8000"
    environment:
      - DATABASE_URL=mysql+pymysql://root:password@db/app_db
      - JWT_SECRET=your_secret_key
    depends_on:
      - db

  db:
    image: mysql:8.0
    container_name: mysql_db
    restart: always
    environment:
      MYSQL_ROOT_USER: root
      MYSQL_ROOT_PASSWORD: password
      MYSQL_DATABASE: app_db
      MYSQL_USER: user
      MYSQL_PASSWORD: user_password
    ports:
      - "3306:3306"
    command: --init-file /data/application/init.sql
    volumes:
      - db_data:/var/lib/mysql  # Persistent data storage
      - ./init.sql:/data/application/init.sql
volumes:
  db_data:

